databases:
  - name: messenger_api
    databaseName: messenger_api
    user: messenger_api

services:
  - type: web
    name: messenger_api
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: messenger_api
          property: connectionString
      - key: <%= File.read('config/master.key') %>
        sync: false